package de.spraener.prjxp.docpipe.content;

import de.spraener.prjxp.common.errorlog.PxLogMessage;
import de.spraener.prjxp.docpipe.config.DotDPFilesService;
import de.spraener.prjxp.docpipe.io.OutputSink;
import de.spraener.prjxp.docpipe.io.OutputSinkFactory;
import de.spraener.prjxp.docpipe.llm.LLMService;
import de.spraener.prjxp.docpipe.model.DPContentCreation;
import de.spraener.prjxp.docpipe.prompt.PromptResolvingService;
import de.spraener.prjxp.docpipe.prompt.TemplateException;
import lombok.RequiredArgsConstructor;
import lombok.extern.java.Log;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.logging.Level;

@Service
@RequiredArgsConstructor
@Log
/**
 * Service responsible for coordinating the creation of documentation content.
 * <p>
 * This service handles the end-to-end process of generating content for a specific task:
 * resolving the prompt, interacting with the LLM, applying post-processing filters,
 * and writing the final result to an output sink.
 * </p>
 */
public class ContentCreationService {
    private final PromptResolvingService promptResolvingService;
    private final LLMService llmService;
    private final ContentUpdateRequiredController updater;
    private final OutputSinkFactory outputSinkFactory;
    private final DotDPFilesService dpFilesService;
    private final de.spraener.prjxp.common.errorlog.PxLogService logService;
    private final List<ContentFilter> contentFilterList;

    /**
     * Creates documentation content for the given task.
     * <p>
     * The process involves resolving the prompt from a template, checking if an update is required,
     * calling the LLM service to generate content, applying any specified filters and post-scripts,
     * and finally writing the result to the designated output file.
     * </p>
     *
     * @param ccTask the task containing the job and content creation configuration
     */
    public void createContent(ContentCreationTask ccTask) {
        try {
            DPContentCreation dpcc = ccTask.getDpContentCreation();

            String prompt = promptResolvingService.resolve(ccTask);
            updater.onUpdateRequired(prompt, ccTask, () -> {
                String outputFile = dpFilesService.getOutputFilePath(ccTask);
                log.info("Creating content of " + outputFile);
                String content = llmService.chat(ccTask, prompt);
                if( StringUtils.hasText(dpcc.getFilterList()) ) {
                    content = applyContentFilters(content, dpcc.getFilterList());
                }
                if (StringUtils.hasText(dpcc.getPs())) {
                    content = content + ccTask.getDpContentCreation().getPs();
                }
                try (OutputSink sink = outputSinkFactory.createSink(Path.of(outputFile))) {
                    sink.println(content);
                } catch (IOException e) {
                    logService.error(e, "Error while trying to create content for %s: %s",
                            ccTask.getDpJob().getRootDir().getAbsolutePath(),  e.getMessage());
                }
            });
        } catch (TemplateException | IOException e) {
            logService.error(e, "Error while trying to create prompt for %s: %s",
                    ccTask.getDpJob().getRootDir().getAbsolutePath(), e.getMessage());
        }
    }

    /**
     * Applies a list of content filters to the generated text.
     * <p>
     * Filters are identified by name in a comma-separated list. If a matching filter is found
     * among the available {@link ContentFilter} beans, it is applied to the content.
     * </p>
     *
     * @param content the raw content generated by the LLM
     * @param filterList a comma-separated list of filter names to apply
     * @return the filtered content
     */
    private String applyContentFilters(String content, String filterList) {
        for(String filterName : filterList.split(",")) {
            ContentFilter filter = contentFilterList.stream()
                .filter(f -> f.name().equals(filterName))
                .findFirst()
                .orElse(null);
            if( filter != null ) {
                content = filter.filter(content);
            }
        }
        return content;
    }
}
