package de.spraener.prjxp.docpipe.content;

import de.spraener.prjxp.docpipe.config.DotDPFilesService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Properties;

@Component
@RequiredArgsConstructor
public class ContentUpdateRequiredController {
    private final DotDPFilesService dpFilesService;

    // Speicherort für die flache Hash-Datenbank

    public void onUpdateRequired(String prompt, ContentCreationTask cct, Runnable updater) {
        String outputFile = cct.getDpContentCreation().getOutputFile();
        if (updateRequired(cct, prompt, outputFile)) {
            updater.run();
            writeEntry(cct, toHash(prompt), outputFile);
        }
    }

    private boolean updateRequired(ContentCreationTask cct, String prompt, String outputFile) {
        String currentHash = toHash(prompt);
        String storedHash = readEntry(cct, outputFile);

        // Update ist erforderlich, wenn noch kein Hash existiert ODER der alte Hash ungleich dem neuen ist
        return storedHash == null || !storedHash.equals(currentHash);
    }

    private String readEntry(ContentCreationTask cct, String outputFile) {
        File file = dpFilesService.getContentHashesFrom(cct);
        if (!file.exists()) {
            return null;
        }

        Properties props = new Properties();
        try (FileInputStream fis = new FileInputStream(file)) {
            props.load(fis);
            return props.getProperty(outputFile);
        } catch (IOException e) {
            // Im Fehlerfall lieber neu generieren lassen
            return null;
        }
    }

    private void writeEntry(ContentCreationTask cct, String hash, String outputFile) {
        File file = dpFilesService.getContentHashesFrom(cct);
        Properties props = new Properties();

        try {
            // 1. Existierende Einträge laden, falls die Datei schon da ist
            if (file.exists()) {
                try (FileInputStream fis = new FileInputStream(file)) {
                    props.load(fis);
                }
            } else {
                // Verzeichnis ".dp" erstellen, falls es noch nicht existiert
                Files.createDirectories(Path.of(file.getParent()));
            }

            // 2. Neuen Wert setzen (überschreibt alten Eintrag für diese Datei)
            props.setProperty(outputFile, hash);

            // 3. Flaches File zurückschreiben
            try (FileOutputStream fos = new FileOutputStream(file)) {
                props.store(fos, "Generated by DocPipe - Do not modify manually");
            }
        } catch (IOException e) {
            throw new IllegalStateException("Fehler beim Schreiben des Hash-Eintrags für " + outputFile, e);
        }
    }

    private String toHash(String prompt) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = digest.digest(prompt.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hashBytes);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 Algorithmus nicht gefunden", e);
        }
    }
}