package de.spraener.prjxp.docpipe.content;

import de.spraener.prjxp.docpipe.config.DotDPFilesService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Properties;

@Component
@RequiredArgsConstructor
/**
 * Controller that determines if documentation content needs to be updated.
 * <p>
 * This class maintains a hash-based database of prompts used to generate specific output files.
 * If the prompt for a task has changed since the last execution, it triggers an update to avoid
 * redundant LLM calls.
 * </p>
 */
public class ContentUpdateRequiredController {
    private final DotDPFilesService dpFilesService;

    // Speicherort für die flache Hash-Datenbank

    /**
     * Checks if an update is required for a given task and executes the updater if so.
     * <p>
     * This method compares the hash of the current prompt with the stored hash for the output file.
     * If they differ or no hash exists, it runs the provided {@code updater} and updates the stored hash.
     * </p>
     *
     * @param prompt the resolved prompt to check
     * @param cct the content creation task
     * @param updater a runnable that performs the actual content generation and writing
     */
    public void onUpdateRequired(String prompt, ContentCreationTask cct, Runnable updater) {
        String outputFile = cct.getDpContentCreation().getOutputFile();
        if (updateRequired(cct, prompt, outputFile)) {
            updater.run();
            writeEntry(cct, toHash(prompt), outputFile);
        }
    }

    /**
     * Determines if the content for a task needs to be updated based on prompt changes.
     *
     * @param cct the content creation task
     * @param prompt the current resolved prompt
     * @param outputFile the path to the output file
     * @return true if an update is required, false otherwise
     */
    private boolean updateRequired(ContentCreationTask cct, String prompt, String outputFile) {
        String currentHash = toHash(prompt);
        String storedHash = readEntry(cct, outputFile);

        // Update ist erforderlich, wenn noch kein Hash existiert ODER der alte Hash ungleich dem neuen ist
        return storedHash == null || !storedHash.equals(currentHash);
    }

    /**
     * Reads the stored hash for a specific output file from the hashes properties file.
     *
     * @param cct the content creation task
     * @param outputFile the path to the output file
     * @return the stored hash string, or null if no entry exists or an error occurs
     */
    private String readEntry(ContentCreationTask cct, String outputFile) {
        File file = dpFilesService.getContentHashesFrom(cct);
        if (!file.exists()) {
            return null;
        }

        Properties props = new Properties();
        try (FileInputStream fis = new FileInputStream(file)) {
            props.load(fis);
            return props.getProperty(outputFile);
        } catch (IOException e) {
            // Im Fehlerfall lieber neu generieren lassen
            return null;
        }
    }

    /**
     * Writes a new hash entry for an output file to the hashes properties file.
     * <p>
     * This method loads existing entries, updates the hash for the specified output file,
     * and writes the updated properties back to the filesystem.
     * </p>
     *
     * @param cct the content creation task
     * @param hash the SHA-256 hash of the prompt
     * @param outputFile the path to the output file
     * @throws IllegalStateException if an IOException occurs during writing
     */
    private void writeEntry(ContentCreationTask cct, String hash, String outputFile) {
        File file = dpFilesService.getContentHashesFrom(cct);
        Properties props = new Properties();

        try {
            // 1. Existierende Einträge laden, falls die Datei schon da ist
            if (file.exists()) {
                try (FileInputStream fis = new FileInputStream(file)) {
                    props.load(fis);
                }
            } else {
                // Verzeichnis ".dp" erstellen, falls es noch nicht existiert
                Files.createDirectories(Path.of(file.getParent()));
            }

            // 2. Neuen Wert setzen (überschreibt alten Eintrag für diese Datei)
            props.setProperty(outputFile, hash);

            // 3. Flaches File zurückschreiben
            try (FileOutputStream fos = new FileOutputStream(file)) {
                props.store(fos, "Generated by DocPipe - Do not modify manually");
            }
        } catch (IOException e) {
            throw new IllegalStateException("Fehler beim Schreiben des Hash-Eintrags für " + outputFile, e);
        }
    }

    /**
     * Computes the SHA-256 hash of a given prompt string.
     *
     * @param prompt the prompt to hash
     * @return the hexadecimal representation of the SHA-256 hash
     * @throws IllegalStateException if the SHA-256 algorithm is not available
     */
    private String toHash(String prompt) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = digest.digest(prompt.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hashBytes);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 Algorithmus nicht gefunden", e);
        }
    }
}