prjxp:
  # which project to work on if none is on command line.
  activeProject: "prjxp"

  projects:
    - name: prjxp
      rootDir: "."
      jsonlFile: "px-chunks.jsonl"
      chunoWhiteList: "java,ts"
      tibedBatchSize: 50
      tibedResetStore: true

  # Use Ollama on SteamDeck for Embedding
  embeddingOllamaUrl: http://192.168.188.114:11434
  embeddingModelName: mxbai-embed-large
  embeddingTimeoutSecs: 60

  embeddingStores:
    - projectName: prjxp
      providerUrl: http://localhost:8000
      tenant: prjxp
      dbName: prjxp
      collectionName: prjxp-src
      isDefault: true


  chatModels:
    - stereoType: documentation
      serverType: gemini
      modelName: gemini-3-flash

    - stereoType: javadoc
      modelName: deepseek-coder-v2:16b
      providerUrl: http://localhost:11434
      serverType: ollama
      timeoutSecs: 120

    - stereoType: faq
      modelName: qwen3.6-31b
      providerUrl: http://localhost:1234/v1
      serverType: lm-studio
      timeoutSecs: 120

    - stereotype: detailed
      serverType: gemini
      modelName: gemini-3-flash-preview
      timeoutSecs: 240

    - stereoType: embedding
      serverType: lm-studio
      providerUrl: http://localhost:1234/v1
      modelName: mxbai-embed-large
      timeoutSecs: 60