mcp:
  cors:
    allowed-patterns: "http://10.*.*.*,http://172.16.*.*,http://192.168.*.*,http://localhost:*"

chat:
  gemini:
    api-key: UNKNOWN
  api-kind: openai
  modelName: gemma-4-31b
  api-key: lm-studio
  api-url: http://192.168.1.224:1234

embedding:
  modelName: mxbai-embed-large
  ollama:
    url: http://localhost:11434

chroma:
  tenant: prjxp
  database: prjxp-enriched
  collectioName: chunk_norris
  url: http://localhost:8000

server:
  forward-headers-strategy: framework
