plugins {
    id 'java-library'
}

dependencies {
    api project(':prjxp-common')

    implementation libs.lucene.core
    implementation libs.langchain4j.core
    implementation libs.langchain4j.community
    implementation libs.opennlp.tools   // Version-Pin: langchain4j zieht opennlp-tools 2.5.4 (Security-CVEs)

    testImplementation libs.bundles.test.bundle
}
