gldrtrvr:
  gemini:
    api-key: UNKNOWN
  chat:
    api-kind: openai
    modelName: gemma-4-31b
    api-url: http://192.168.1.224:1234
    api-key: lm-studio

  embedding:
    modelName: mxbai-embed-large
    ollamaBaseUrl: http://localhost:11434
    chroma:
      collectioName: chunk_norris
      database: prjxp
      tenant: prjxp


  chromaBaseUrl: http://localhost:8000
  chromaCollectionName: chunk_norris
