prjxp:
  transfer:
    password-env: PRJXP_TRANSFER_PASSWORD
    encrypt: auto
    mode: store

  embedding:
    type: OLLAMA
    apiBaseURL: http://192.168.1.140:11434
    modelName: mxbai-embed-large

