### GET request to example server
GET http://localhost:8080/prjxp/tools/ping

###

GET http://localhost:8080/prjxp/tools/context?project=prjxp&userQuestion=Wie%20funktioniert%20die%20Dokument-Konvertierung%20in%20Chunk-Norris

###
